{
 "title": "DCS-Redis",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "listRegions()" },
   {
    "name": "dcs_instance_id",
    "label": "Redis-instance",
    "query": "listDims($region,SYS.DCS,dcs_instance_id,dcs_instance_id)"
   },
   {
    "name": "dcs_cluster_redis_node",
    "label": "node",
    "query": "listDims($region,SYS.DCS,dcs_cluster_redis_node;$dcs_instance_id,dcs_cluster_redis_node)"
   },
   {
    "name": "dcs_cluster_proxy2_node",
    "label": "Proxy",
    "query": "listDims($region,SYS.DCS,dcs_cluster_proxy2_node;$dcs_instance_id,dcs_cluster_proxy2_node)"
   },
   { "name": "filter", "label": "Filter", "query": "listFilterOptions()" },
   { "name": "period", "label": "Period", "query": "listPeriodOptions()" }
  ]
 },
 "panels": [
  { "title": "instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "memory_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "bandwidth_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "ops per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "ops_per_second",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "keys",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "flow control times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "flow_control_times",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "slow query logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "dimstr": "dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "slow_query_logs",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  { "title": "node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "memory_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "cpu_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "bandwidth_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "ops per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "ops_per_second",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "keys",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "slow query logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_redis_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "slow_query_logs",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_proxy2_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "memory_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimstr": "dcs_cluster_proxy2_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "cpu_usage",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  },
  {
   "title": "ops per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "dimstr": "dcs_cluster_proxy2_node:00000000000000000000000000000000,dcs_instance_id:00000000-0000-0000-0000-000000000000",
     "filter": "average",
     "metricName": "ops_per_second",
     "namespace": "SYS.DCS",
     "period": "1",
     "region": "-"
    }
   ]
  }
 ]
}